package com.mambu.back.enums;

public enum PreferredLanguage {
    ENGLISH, PORTUGESE, SPANISH, RUSSIAN, FRENCH, GEORGIAN, CHINESE, INDONESIAN, ROMANIAN, BURMESE, GERMAN, PORTUGUESE_BRAZIL, VIETNAMESE, ITALIAN, PHRASE
}
